# Generated by Django 4.2.14 on 2026-04-20 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
